service: appd-lambda-nodejs

provider:
  name: aws
  runtime: nodejs10.x
  environment:
    # replace these env variables with your controller info values
    APPDYNAMICS_ACCOUNT_NAME: 
    APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: 
    APPDYNAMICS_APPLICATION_NAME: 
    APPDYNAMICS_CONTROLLER_HOST: 
    APPDYNAMICS_CONTROLLER_PORT: 
    APPDYNAMICS_LOG_LEVEL: DEBUG
    APPDYNAMICS_SERVERLESS_API_ENDPOINT: 

package:
  exclude:
    - "*.test.js"

functions:
  lambda-1:
    handler: handler.doFunctionAsync
    description: Sample Lambda function in NodeJS for AppD Lambda Instrumentation
    memorySize: 256
    timeout: 30
    environment:
      APPDYNAMICS_TIER_NAME: ${self:service}-lambda-1
    events:
      - http:
          path: /{proxy+}
          method: any    

  lambda-2:
    handler: handler.doFunctionAsync2
    description: Second sample Lambda function
    memorySize: 256
    timeout: 30
    environment:
      APPDYNAMICS_TIER_NAME: ${self:service}-lambda-2
